pipeline {
    environment {
        commitAuthor = ""
    }

    agent any

    tools {
        nodejs "node-12"
    }

    stages {
        stage("Cloning git") {
            steps {
                git branch: "master",
                        credentialsId: "github-username",
                        url: "https://github.com/Jamsek-m/ngx-keycloak-service"
            }
        }
        stage("Set environment variables") {
            steps {
                script {
                    sh "git --no-pager show -s --format='%ae' > COMMIT_INFO"
                    commitAuthor = readFile("COMMIT_INFO").trim()
                }
            }
        }
        stage("Install dependencies") {
            steps {
                withNPM(npmrcConfig: 'npm-public-file') {
                    sh "npm install"
                }
            }
        }
        stage("Deploy library") {
            steps {
                withNPM(npmrcConfig: 'npm-snapshot-file') {
                    sh "npm run publish:lib"
                }
            }
        }
    }
    post {
        success {
            slackSend (color: '#00FF00', message: "SUCCESSFUL: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' from ${commitAuthor} (${env.BUILD_URL})")
        }
        failure {
            slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' from ${commitAuthor} (${env.BUILD_URL})")
        }
    }
}
